name: Run Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python src/scrape_cdkeys.py

      - name: Upload output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-output
          path: |
            data/*
            *.log
            *.png